# Generated by Django 3.0.1 on 2019-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
            preserve_default=False,
        ),
    ]
